version: "3"
services:
  front:
    image: 127.0.0.1:5000/demo/front:1.0
    build: ./front
    ports:
      - 3000:3000
    depends_on:
      - back
  back:
    image: 127.0.0.1:5000/demo/back:1.0
    build: ./back
    depends_on:
      - redis
  redis:
    image: redis:4.0-alpine
